/**
 * discord.jsのPermissionFlagsBitsのキー名・ビット値と表示用の日本語権限名の対応表。
 * dashboard-webはdiscord.js(サーバー向けの重い依存)を持ち込めないため、ビット値を
 * 直接この配列で保持する。keyとbitがPermissionFlagsBitsと一致しているかは
 * packages/logging側のテストで検証し、Discordに権限が追加された際の追記漏れを検知する
 * (issue #225)。新しい権限が追加された場合はここにも追記する。
 */
export const DISCORD_PERMISSION_LABELS: ReadonlyArray<{ key: string; bit: bigint; label: string }> = [
  { key: "CreateInstantInvite", bit: 1n << 0n, label: "招待を作成" },
  { key: "KickMembers", bit: 1n << 1n, label: "メンバーをキック" },
  { key: "BanMembers", bit: 1n << 2n, label: "メンバーをBAN" },
  { key: "Administrator", bit: 1n << 3n, label: "管理者" },
  { key: "ManageChannels", bit: 1n << 4n, label: "チャンネルの管理" },
  { key: "ManageGuild", bit: 1n << 5n, label: "サーバーの管理" },
  { key: "AddReactions", bit: 1n << 6n, label: "リアクションの追加" },
  { key: "ViewAuditLog", bit: 1n << 7n, label: "監査ログを表示" },
  { key: "PrioritySpeaker", bit: 1n << 8n, label: "優先スピーカー" },
  { key: "Stream", bit: 1n << 9n, label: "配信" },
  { key: "ViewChannel", bit: 1n << 10n, label: "チャンネルを見る" },
  { key: "SendMessages", bit: 1n << 11n, label: "メッセージを送信" },
  { key: "SendTTSMessages", bit: 1n << 12n, label: "テキスト読み上げメッセージを送信" },
  { key: "ManageMessages", bit: 1n << 13n, label: "メッセージの管理" },
  { key: "EmbedLinks", bit: 1n << 14n, label: "埋め込みリンク" },
  { key: "AttachFiles", bit: 1n << 15n, label: "ファイルを添付" },
  { key: "ReadMessageHistory", bit: 1n << 16n, label: "メッセージ履歴を読む" },
  { key: "MentionEveryone", bit: 1n << 17n, label: "@everyone、@here、全ロールにメンション" },
  { key: "UseExternalEmojis", bit: 1n << 18n, label: "外部の絵文字を使用" },
  { key: "ViewGuildInsights", bit: 1n << 19n, label: "サーバーインサイトを見る" },
  { key: "Connect", bit: 1n << 20n, label: "接続" },
  { key: "Speak", bit: 1n << 21n, label: "発言" },
  { key: "MuteMembers", bit: 1n << 22n, label: "メンバーをミュート" },
  { key: "DeafenMembers", bit: 1n << 23n, label: "メンバーのスピーカーをミュート" },
  { key: "MoveMembers", bit: 1n << 24n, label: "メンバーを移動" },
  { key: "UseVAD", bit: 1n << 25n, label: "音声検出を使用" },
  { key: "ChangeNickname", bit: 1n << 26n, label: "ニックネームの変更" },
  { key: "ManageNicknames", bit: 1n << 27n, label: "ニックネームの管理" },
  { key: "ManageRoles", bit: 1n << 28n, label: "ロールの管理" },
  { key: "ManageWebhooks", bit: 1n << 29n, label: "ウェブフックの管理" },
  { key: "ManageGuildExpressions", bit: 1n << 30n, label: "サーバーの絵文字・ステッカー・サウンドの管理" },
  { key: "UseApplicationCommands", bit: 1n << 31n, label: "アプリケーションコマンドの使用" },
  { key: "RequestToSpeak", bit: 1n << 32n, label: "発言をリクエスト" },
  { key: "ManageEvents", bit: 1n << 33n, label: "イベントの管理" },
  { key: "ManageThreads", bit: 1n << 34n, label: "スレッドの管理" },
  { key: "CreatePublicThreads", bit: 1n << 35n, label: "公開スレッドの作成" },
  { key: "CreatePrivateThreads", bit: 1n << 36n, label: "非公開スレッドの作成" },
  { key: "UseExternalStickers", bit: 1n << 37n, label: "外部のステッカーを使用" },
  { key: "SendMessagesInThreads", bit: 1n << 38n, label: "スレッドにメッセージを送信" },
  { key: "UseEmbeddedActivities", bit: 1n << 39n, label: "アクティビティを使用" },
  { key: "ModerateMembers", bit: 1n << 40n, label: "メンバーをタイムアウト" },
  { key: "ViewCreatorMonetizationAnalytics", bit: 1n << 41n, label: "クリエイターの収益化アナリティクスを見る" },
  { key: "UseSoundboard", bit: 1n << 42n, label: "サウンドボードを使用" },
  { key: "CreateGuildExpressions", bit: 1n << 43n, label: "絵文字・ステッカー・サウンドの作成" },
  { key: "CreateEvents", bit: 1n << 44n, label: "イベントの作成" },
  { key: "UseExternalSounds", bit: 1n << 45n, label: "外部のサウンドを使用" },
  { key: "SendVoiceMessages", bit: 1n << 46n, label: "ボイスメッセージを送信" },
  { key: "SetVoiceChannelStatus", bit: 1n << 48n, label: "ボイスチャンネルステータスの設定" },
  { key: "SendPolls", bit: 1n << 49n, label: "投票を作成" },
  { key: "UseExternalApps", bit: 1n << 50n, label: "外部アプリを使用" },
  { key: "PinMessages", bit: 1n << 51n, label: "メッセージをピン留め" },
  { key: "BypassSlowmode", bit: 1n << 52n, label: "低速モードを回避" },
];
